# Generated by Django 4.1.1 on 2022-09-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_username', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_avatar_url', models.URLField(blank=True, default='', null=True)),
                ('candidate_url', models.URLField(blank=True, default='', null=True)),
                ('candidate_company', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_blog_url', models.URLField(blank=True, default='', null=True)),
                ('candidate_location', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_email', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('candidate_bio', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('candidate_repo_number', models.IntegerField(blank=True, default='', null=True)),
                ('candidate_gists_number', models.IntegerField(blank=True, default='', null=True)),
                ('candidate_follower_number', models.IntegerField(blank=True, default='', null=True)),
                ('candidate_following_number', models.IntegerField(blank=True, default='', null=True)),
                ('candidate_join_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('candidate_notes', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('stackoverflow_candidate_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('stackoverflow_candidate_url', models.URLField(blank=True, default='', null=True)),
                ('stackoverflow_candidate_avatar_url', models.URLField(blank=True, default='', null=True)),
                ('stackoverflow_candidate_blog_url', models.URLField(blank=True, default='', null=True)),
                ('stackoverflow_candidate_location', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('stackoverflow_candidate_bio', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('stackoverflow_candidate_view_count', models.IntegerField(blank=True, default='', null=True)),
                ('stackoverflow_candidate_up_vote_count', models.IntegerField(blank=True, default='', null=True)),
                ('stackoverflow_candidate_answer_count', models.IntegerField(blank=True, default=0, null=True)),
                ('stackoverflow_candidate_question_count', models.IntegerField(blank=True, default='', null=True)),
                ('stackoverflow_candidate_reputation', models.IntegerField(blank=True, default='', null=True)),
            ],
        ),
    ]
