# Generated by Django 4.1.1 on 2022-09-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_for_candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='stackoverflow_candidate_answer_count',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stackoverflow_candidate_question_count',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stackoverflow_candidate_reputation',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stackoverflow_candidate_up_vote_count',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stackoverflow_candidate_view_count',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
